USE [master]
GO
/****** Object:  Database [FizzBuzzSolver]    Script Date: 2/21/2022 9:13:22 PM ******/
CREATE DATABASE [FizzBuzzSolver]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'FizzBuzzSolver', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\FizzBuzzSolver.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'FizzBuzzSolver_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\FizzBuzzSolver_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [FizzBuzzSolver] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [FizzBuzzSolver].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [FizzBuzzSolver] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [FizzBuzzSolver] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [FizzBuzzSolver] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [FizzBuzzSolver] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [FizzBuzzSolver] SET ARITHABORT OFF 
GO
ALTER DATABASE [FizzBuzzSolver] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [FizzBuzzSolver] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [FizzBuzzSolver] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [FizzBuzzSolver] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [FizzBuzzSolver] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [FizzBuzzSolver] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [FizzBuzzSolver] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [FizzBuzzSolver] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [FizzBuzzSolver] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [FizzBuzzSolver] SET  DISABLE_BROKER 
GO
ALTER DATABASE [FizzBuzzSolver] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [FizzBuzzSolver] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [FizzBuzzSolver] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [FizzBuzzSolver] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [FizzBuzzSolver] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [FizzBuzzSolver] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [FizzBuzzSolver] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [FizzBuzzSolver] SET RECOVERY FULL 
GO
ALTER DATABASE [FizzBuzzSolver] SET  MULTI_USER 
GO
ALTER DATABASE [FizzBuzzSolver] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [FizzBuzzSolver] SET DB_CHAINING OFF 
GO
ALTER DATABASE [FizzBuzzSolver] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [FizzBuzzSolver] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [FizzBuzzSolver] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [FizzBuzzSolver] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'FizzBuzzSolver', N'ON'
GO
ALTER DATABASE [FizzBuzzSolver] SET QUERY_STORE = OFF
GO
USE [FizzBuzzSolver]
GO
/****** Object:  Table [dbo].[Divisors]    Script Date: 2/21/2022 9:13:22 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Divisors](
	[DivisorId] [int] IDENTITY(1,1) NOT NULL,
	[NumericValue] [bigint] NOT NULL,
	[PrintableOutput] [varchar](max) NOT NULL,
 CONSTRAINT [PK_Divisors] PRIMARY KEY CLUSTERED 
(
	[DivisorId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Errors]    Script Date: 2/21/2022 9:13:22 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Errors](
	[ErrorId] [int] IDENTITY(1,1) NOT NULL,
	[Title] [varchar](max) NOT NULL,
	[Description] [varchar](max) NULL,
 CONSTRAINT [PK_Errors] PRIMARY KEY CLUSTERED 
(
	[ErrorId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[RequestDivisors]    Script Date: 2/21/2022 9:13:22 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[RequestDivisors](
	[RequestDivisorId] [int] IDENTITY(1,1) NOT NULL,
	[RequestId] [int] NOT NULL,
	[DivisorId] [int] NOT NULL,
 CONSTRAINT [PK_RequestDivisors] PRIMARY KEY CLUSTERED 
(
	[RequestDivisorId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[RequestErrors]    Script Date: 2/21/2022 9:13:22 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[RequestErrors](
	[RequestErrorId] [int] NOT NULL,
	[RequestId] [int] NOT NULL,
	[ErrorId] [int] NOT NULL,
	[CustomMessage] [int] NOT NULL,
	[CreatedDateTime] [datetime] NOT NULL,
 CONSTRAINT [PK_RequestErrors] PRIMARY KEY CLUSTERED 
(
	[RequestErrorId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Requests]    Script Date: 2/21/2022 9:13:22 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Requests](
	[RequestId] [int] IDENTITY(1,1) NOT NULL,
	[IsSuccess] [bit] NOT NULL,
	[MaxNumber] [bigint] NOT NULL,
	[CreatedDateTime] [datetime] NOT NULL,
 CONSTRAINT [PK_Requests] PRIMARY KEY CLUSTERED 
(
	[RequestId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ResponseResults]    Script Date: 2/21/2022 9:13:22 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ResponseResults](
	[ResponseResultId] [int] IDENTITY(1,1) NOT NULL,
	[ResponseId] [int] NOT NULL,
	[Position] [bigint] NOT NULL,
	[OutputValue] [varchar](max) NOT NULL,
 CONSTRAINT [PK_ResponseResults] PRIMARY KEY CLUSTERED 
(
	[ResponseResultId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Responses]    Script Date: 2/21/2022 9:13:22 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Responses](
	[ResponseId] [int] IDENTITY(1,1) NOT NULL,
	[RequestId] [int] NOT NULL,
	[CreatedDateTime] [datetime] NOT NULL,
 CONSTRAINT [PK_Responses] PRIMARY KEY CLUSTERED 
(
	[ResponseId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Divisors]  WITH CHECK ADD  CONSTRAINT [FK_Divisors_Divisors] FOREIGN KEY([DivisorId])
REFERENCES [dbo].[Divisors] ([DivisorId])
GO
ALTER TABLE [dbo].[Divisors] CHECK CONSTRAINT [FK_Divisors_Divisors]
GO
ALTER TABLE [dbo].[RequestDivisors]  WITH CHECK ADD  CONSTRAINT [FK_RequestDivisors_Divisors] FOREIGN KEY([DivisorId])
REFERENCES [dbo].[Divisors] ([DivisorId])
GO
ALTER TABLE [dbo].[RequestDivisors] CHECK CONSTRAINT [FK_RequestDivisors_Divisors]
GO
ALTER TABLE [dbo].[RequestDivisors]  WITH CHECK ADD  CONSTRAINT [FK_RequestDivisors_Requests] FOREIGN KEY([RequestId])
REFERENCES [dbo].[Requests] ([RequestId])
GO
ALTER TABLE [dbo].[RequestDivisors] CHECK CONSTRAINT [FK_RequestDivisors_Requests]
GO
ALTER TABLE [dbo].[RequestErrors]  WITH CHECK ADD  CONSTRAINT [FK_RequestErrors_Errors] FOREIGN KEY([ErrorId])
REFERENCES [dbo].[Errors] ([ErrorId])
GO
ALTER TABLE [dbo].[RequestErrors] CHECK CONSTRAINT [FK_RequestErrors_Errors]
GO
ALTER TABLE [dbo].[RequestErrors]  WITH CHECK ADD  CONSTRAINT [FK_RequestErrors_Requests] FOREIGN KEY([RequestId])
REFERENCES [dbo].[Requests] ([RequestId])
GO
ALTER TABLE [dbo].[RequestErrors] CHECK CONSTRAINT [FK_RequestErrors_Requests]
GO
ALTER TABLE [dbo].[Responses]  WITH CHECK ADD  CONSTRAINT [FK_Responses_Requests] FOREIGN KEY([RequestId])
REFERENCES [dbo].[Requests] ([RequestId])
GO
ALTER TABLE [dbo].[Responses] CHECK CONSTRAINT [FK_Responses_Requests]
GO
USE [master]
GO
ALTER DATABASE [FizzBuzzSolver] SET  READ_WRITE 
GO
